### PR TITLE
Removed the LuckPerms service cache

### PR DESCRIPTION
**Pull request by jordanamr**

### CODE REVIEW

**Comment by STG-Allen** [comment]
Can you test this with two groups that have different tags and make sure they update in-game and in the tab?

**Comment by jordanamr** [comment]
Seems to work fine, if the two weights are exactly the same for both prefix and group, it takes one of the two groups (probably based on the group ID internally in luckperms), if you have the same weight in both the user meta and a group meta, the prefix will use the user meta.
If the two prefix weights are different, it takes the highest one.
This is the intended LuckPerms meta behaviour and everything updates fine for me !

**Comment by STG-Allen** [comment]
I'm going to do a live test of this before I merge it, had issues with this setup before and just wanna make sure it's not gonna persist so we don't have users with issues in the future (previously i had nucleus controlling chat and it worked with my setup)

**Comment by jordanamr** [comment]
I am using Catalyst to control the chat and it works, unsure a bout Nucleus as I never used it.
I would love to see more tests

**Comment by jordanamr** [comment]
Rebased

**Comment by jordanamr** [comment]
Rebased

**Pull request merged**
